# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-16 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weibo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.CharField(default=0, max_length=20, verbose_name='账号'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='user_name',
            field=models.CharField(default=0, max_length=200, verbose_name='姓名'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='suggest',
            name='phone',
            field=models.CharField(max_length=11, verbose_name='联系电话'),
        ),
    ]
